AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Boilerplate Go API.'
Resources:
  GoAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-go-serverless-api
      Runtime: go1.x
      CodeUri: lambda-go-serverless-api
      Events:
        Greedy:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
        ProxyApiRoot:
          Type: Api
          Properties:
            Method: ANY
            Path: /

Outputs:
  EndpointUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
